### PR TITLE
Switch to using a variant that is not already present.

### LINKED ISSUE #4: `noblas` version isn't being built
See https://github.com/conda-forge/conda-smithy/issues/1025

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Solves some weird override issues in conda render

closes #4 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by tadeu** [comment]
Should the build number be bumped now?

**Comment by tadeu** [comment]
What happens with `blas_impl` comming from pinnings, will it be completely ignored? (I don't know if it's used elsewhere by conda-forge & conda-build)

**Comment by mariusvniekerk** [comment]
Yep its ignored

**Pull request merged**
