### PR TITLE
updated v1.3.7

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by tadeu** [comment]
Hmm, it had some CMake changes in upstream, I guess this made some tests fail, I'll take a look

**Comment by jschueller** [comment]
yes, the cmake config file changed location, and it seems the patches still apply, do you think they have been upstreamed ?

**Comment by tadeu** [comment]
> and it seems the patches still apply, do you think they have been upstreamed ?

No, it still tests `tlmdif` upstream, but maybe in this new version the results are matching, but this is minor, I think that it's okay to keep applying the patches.

**Review by tadeu — APPROVED** [review]

**Review by tadeu — CHANGES_REQUESTED** [review]
Hmm, Windows is still failing, I'll take a look at this, but I need some time to reproduce it locally

**Comment by tadeu** [comment]
Oh no, all results are different in Windows when running in Azure 😮

```
Test project D:/bld/cminpack_1610032852505/work/build
      Start  1: tchkder_
 1/24 Test  #1: tchkder_ .........................***Failed    0.09 sec
Running: D:/bld/cminpack_1610032852505/work/build/examples/tchkder_.exe

(...)

      Start 24: tfdjac2c
24/24 Test #24: tfdjac2c .........................***Failed    0.09 sec
Running: D:/bld/cminpack_1610032852505/work/build/examples/tfdjac2c.exe
ARGS= OUTPUT_FILE;D:/bld/cminpack_1610032852505/work/build/examples/tfdjac2c.out;ERROR_FILE;D:/bld/cminpack_1610032852505/work/build/examples/tfdjac2c.out.err
CMake Error at D:/bld/cminpack_1610032852505/work/examples/runtest.cmake:34 (message):
  Test D:/bld/cminpack_1610032852505/work/build/examples/tfdjac2c.exe
  produced a result which is different from the reference}

(...)

0% tests passed, 24 tests failed out of 24

Total Test time (real) =   2.01 sec

The following tests FAILED:
	  1 - tchkder_ (Failed)
	  2 - tchkderc (Failed)
	  3 - thybrd_ (Failed)
	  4 - thybrdc (Failed)
	  5 - thybrd1_ (Failed)
	  6 - thybrd1c (Failed)
	  7 - thybrj_ (Failed)
	  8 - thybrjc (Failed)
	  9 - thybrj1_ (Failed)
	 10 - thybrj1c (Failed)
	 11 - tlmder_ (Failed)
	 12 - tlmderc (Failed)
	 13 - tlmder1_ (Failed)
	 14 - tlmder1c (Failed)
	 15 - tlmdif_ (Failed)
	 16 - tlmdifc (Failed)
	 17 - tlmdif1_ (Failed)
	 18 - tlmdif1c (Failed)
	 19 - tlmstr_ (Failed)
	 20 - tlmstrc (Failed)
	 21 - tlmstr1_ (Failed)
	 22 - tlmstr1c (Failed)
	 23 - tfdjac2_ (Failed)
	 24 - tfdjac2c (Failed)
```

Locally they are passing, though :(

**Comment by jschueller** [comment]
seems unix2dos is missing, so the ref files are not converted and the tests fail

**Comment by tadeu** [comment]
I've tried forcing Windows builds to also use libblas (MKL by default), no avail :/

**Comment by tadeu** [comment]
> seems unix2dos is missing, so the ref files are not converted and the tests fail

hmmm, good catch!
indeed, `unix2dos` is being used locally here

**Comment by jschueller** [comment]
good!

**Comment by tadeu** [comment]
Thanks, @jschueller 😄

**Pull request merged**
